language: python

python:
  - "2.6"
  - "2.7"

install:
  - python setup.py install
  - pip install coveralls

script: nosetests

after_success:
  - nosetests --with-coverage --cover-package=flask_analytics --cover-html
  - coveralls
